<?php

########################################################################
# Extension Manager/Repository config file for ext: "mm_messaging"
#
# Auto generated by Extbase Kickstarter 2010-10-08
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'mm_forum Messenger',
	'description' => 'This extention includes the privat messaging between users',
	'category' => 'plugin',
	'author' => 'Martin Helmich,Ruven Fehling',
	'author_email' => 'm.helmich@mittwald.de,r.fehling@mittwald.de',
	'author_company' => 'Mittwald CM Service GmbH & Co. KG,Mittwald CM Service GmbH & Co. KG',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>